# Generated by Django 4.2.23 on 2025-08-14 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="citation",
            unique_together={("source_article", "target_article")},
        ),
    ]
